# Generated by Django 5.2.4 on 2025-07-27 17:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myapp', '0002_delete_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('customer_name', models.CharField(max_length=100)),
                ('material', models.CharField(max_length=100)),
                ('quantity', models.FloatField()),
                ('rate', models.FloatField()),
            ],
        ),
    ]
