# Generated by Django 5.2.4 on 2025-08-02 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
