# Generated by Django 5.2.4 on 2025-08-03 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='bill',
        ),
        migrations.DeleteModel(
            name='Bill',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
